### ISSUE TITLE
[Send Confirmation modal] Cannot see buttons and cannot scroll 

### ISSUE THREAD

**Issue by wrt-github** [mobilecoinofficial/desktop-wallet#107] opened 2021-04-10 19:26 UTC
### Machine

MobileCoin-Desktop-Wallet-beta-v030
macOS Big Sur 11.2.3
Display: 15.4-inch (2880 × 1800)

### Description

In this screenshot below, you can see the bounds of the window:

<img width="812" alt="send-button-scroll-cut-off" src="https://user-images.githubusercontent.com/82286902/114282646-f6b69780-99f9-11eb-97eb-c44fbda4d2ba.png">

I cannot scroll the content.

I tried resizing the window by dragging the edges of the window. While I was able to resize the window, resizing does not help because the modal is a fixed width in the center of the page.

This issue prevents sending MOB.

### Reproducing the bug

First, generate a long address. On the Signal phone app, navigate to **Signal Settings > Payments > Add Money**. Tap **Copy** to copy the wallet address linked to your Signal account.

> **Note**: The Signal phone app generates a 258-character address. I think that means it is an Assigned Address, because my Public Address is only 107 characters. The length of the 258-character address seems to be causing the problem.

Click the **Send/Receive** tab at the top of the app. Paste the address you got from Signal into the **Recipient's Public Address**. Type a small number in **MOB Amount**. Click **Send Payment**. 

You will be presented with a modal confirmation. You'll need to click a button to confirm the send, but because you cannot scroll the content, you cannot see which button to click.

**Comment by sweah** [comment] 2021-04-13 06:19
Same here. Buttons are out of range and scolling not possible:
Ubuntu 20.10
MobileCoin-Desktop-Wallet-beta-v030
Display: 13.3" 1366x768

**Comment by johnedma** [comment] 2021-04-13 17:24
@sweah @wrt-github Hey folks, please verify but the the fix should have been merged into main for the modal sometime yesterday afternoon, if the issue is still there please let me know https://github.com/mobilecoinofficial/desktop-wallet/pull/109

**Comment by wrt-github** [comment] 2021-04-13 19:55
@johnedma I was able to get the **main** branch installed and launched with the Electron using `yarn dev`. However, I cannot launch the Send Confirmation modal because I don't have any MOB in the wallet. What is the best practice to get MOB in the wallet so that I can play with the interface in the dev mode?

**Comment by voloshyn** [comment] 2021-04-20 19:23
> @johnedma I was able to get the **main** branch installed and launched with the Electron using `yarn dev`. However, I cannot launch the Send Confirmation modal because I don't have any MOB in the wallet. What is the best practice to get MOB in the wallet so that I can play with the interface in the dev mode?
> 
> **EDIT**: I think I can get Testnet up and running by installing the release from https://github.com/mobilecoinofficial/full-service/releases and putting that into the **full-service-bin** directory. However, it looks like obtaining the `ingest-enclave` binary is more difficult though.

Check out [Full-Service README](https://github.com/mobilecoinofficial/full-service/blob/main/README.md) for the info on where to get the binary files.

**Closed** 2021-04-20 19:23 UTC

**Comment by sweah** [comment] 2021-07-09 07:14
> Same here. Buttons are out of range and scolling not possible:
> Ubuntu 20.10 
> MobileCoin-Desktop-Wallet-beta-v030
> Display: 13.3" 1366x768

I have installed MobileCoin-Desktop-Wallet-beta-v040 now and I still have the same problems with inaccessable Buttons. I see them in Xorg and Wayland sessions, The height is not adjustable, so it is impossible to get to the buttons.

![mob](https://user-images.githubusercontent.com/1198892/125038504-c680a280-e095-11eb-916b-fea8b5062bd9.jpeg)
